/* 
 * File:   app_ble_task.h
 * Author: C18797
 *
 * Created on July 22, 2022, 10:55 AM
 */

#ifndef APP_BLE_TASK_H
#define	APP_BLE_TASK_H

#ifdef	__cplusplus
extern "C" {
#endif
    
#define APP_BLE_STATE_MASK 0xFF00
#define APP_BLE_NOTIF_CALLBACK_COUNT 16

typedef enum
{
    APP_BLE_STATE_INIT = 0x0000,
    APP_BLE_STATE_MODULE_INIT,
    APP_BLE_STATE_SYSFS_MOUNT,
    APP_BLE_STATE_GET_DEV_ADDR,
    APP_BLE_STATE_IDLE,
    APP_BLE_STATE_PROCESS_NOTIF,
    APP_BLE_STATE_WAIT,
            
    APP_BLE_STATE_SCANNING = 0x0100,
    APP_BLE_STATE_SCAN_START = APP_BLE_STATE_SCANNING,
    APP_BLE_STATE_SCAN_SCANNING,
    APP_BLE_STATE_SCAN_SCAN_PROCESSING,
    APP_BLE_STATE_SCAN_STOPPING,
    APP_BLE_STATE_SCAN_COMPLETE,
    APP_BLE_STATE_SCAN_FAILED,
    
    //Connect states
    APP_BLE_STATE_CONNECTING = 0x0200,
    APP_BLE_STATE_CONNECT_START = APP_BLE_STATE_CONNECTING,
    APP_BLE_STATE_CONNECT_CONNECTING,
    APP_BLE_STATE_CONNECT_CONNECTED_GETSTATE,
    APP_BLE_STATE_CONNECT_CONNECTED_INIT,
    APP_BLE_STATE_CONNECT_CONNECTED_GETHANDLE,
    APP_BLE_STATE_CONNECT_CONNECTED,
    APP_BLE_STATE_CONNECT_CONNECTED_CTRL_SET,
    APP_BLE_STATE_CONNECT_CONNECTED_CTRL_GET,
    APP_BLE_STATE_CONNECT_CONNECTED_CTRL_SET_DONE,
    APP_BLE_STATE_CONNECT_FAILED,
    APP_BLE_STATE_CONNECT_INIT_FAILED,
            
    //Multi-link Connect/Connected states
    APP_BLE_STATE_ML_CONNECTING = 0x0400,
    APP_BLE_STATE_ML_CONNECT_INIT = APP_BLE_STATE_ML_CONNECTING,
    APP_BLE_STATE_ML_CONNECT_START,
    APP_BLE_STATE_ML_CONNECT_CONNECTING,
    APP_BLE_STATE_ML_CONNECT_CONNECTING_WAIT,            
    APP_BLE_STATE_ML_CONNECT_CONNECTED_GETSTATE,
    APP_BLE_STATE_ML_CONNECT_CONNECTED,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_CTRL_INIT,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_CTRL_CHECK,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_CTRL_READY,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_CTRL_SET,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_ML_CTRL_SET,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_CTRL_SET_DONE,
    APP_BLE_STATE_ML_CONNECT_FAILED,
    APP_BLE_STATE_ML_CONNECT_DEVICE_FAILED,
    APP_BLE_STATE_ML_CONNECT_CONNECTED_ML_CTRL_FAILED,
    
    APP_BLE_STATE_DISCONNECTING = 0x0800,
    APP_BLE_STATE_DISCONNECT_START = APP_BLE_STATE_DISCONNECTING,
    APP_BLE_STATE_DISCONNECT_DISCONNECTING,
    APP_BLE_STATE_DISCONNECT_DISCONNECTED,
    APP_BLE_STATE_DISCONNECT_FAILED,
            
    APP_BLE_STATE_WRITING = 0x0500,
    APP_BLE_STATE_WRITE_START = APP_BLE_STATE_WRITING,
} APP_BLE_TASK_STATE;

typedef enum
{
    APP_BLE_STATE_CHANGE,               //BLE Task state change event
    APP_BLE_SCAN_COUNT_NOTIFY,          //BLE Scan Count Update
    APP_BLE_DEVICE_NOTIFY,              //BLE device notification Event
} APP_BLE_NOTIFY_EVENT;

typedef struct
{
    void (*func) (uint32_t event, void * data, uint32_t size);
} APP_BLE_NOTIF_CALLBACK;

typedef struct
{
    APP_BLE_TASK_STATE taskState;
    APP_BLE_TASK_STATE nextState;
//    QueueHandle_t msgQueue;
    APP_BLE_NOTIF_CALLBACK notifCallbacks[APP_BLE_NOTIF_CALLBACK_COUNT];
    SYS_FS_HANDLE cfgFileHandle;
} APP_BLE_TASK_OBJ;

void APP_BLE_Initialize(void);
void APP_BLE_Tasks (void);

extern APP_BLE_TASK_OBJ appBleTask;
#ifdef	__cplusplus
}
#endif

#endif	/* APP_BLE_TASK_H */

